### ISSUE TITLE
Directories outside of /home/[user] do not work

### ISSUE THREAD

**Issue by parafoxia** [MrDogeBro/quicknav#17]
## Bug Description
`quicknav` automatically prefixes any set directories with `/home/[user]` so in the case you need to navigate to something on a different drive for example (like `/mnt/Data`) it errors.

## Reproduction
`quicknav add test /anywhere/that/isnt/in/home`

## Expected Behavior
The shortcut sets.

## Screenshots
![image](https://user-images.githubusercontent.com/43846948/118904103-1605e600-b911-11eb-8751-9b15b285bed3.png)

## Info
- OS Name and Version: Windows 10
- Quicknav Version: 1.0.1
- Shell: ZSH

**Comment by parafoxia** [comment]
If anyone sees this before update, you can fix this issue by manually editing the `~/.config/quicknav/quicknav.json` file.

**Comment by MrDogeBro** [comment]
Yeah, its just an issue with the add command so I think it should not be too hard to fix (hopefully).
