### ISSUE TITLE
Multiple calls are stored weird

### ISSUE THREAD

**Issue by parafoxia** [MrDogeBro/quicknav#20]
## Problem/Description
This is an FR as the current method is intentional, but I think it's a little clunky. Essentially, the `calls` in the config can have multiple entries, but the `nav add` adds a whole new nav entry. Perhaps an aliasing system could work. Also, using `nav remove` on a nav entry with multiple calls removes the whole thing. Again perhaps one at a time, and maybe a flag (`-a / --all`) to remove all calls the entire thing if there are more than one.

## Desired Solution
A slightly less clunky system. More QOL, streamlining, etc.

## Considered Alternatives
Removing the multiple calls capability and have them all as their own entry,

**Comment by MrDogeBro** [comment]
What do you think about a param for adding and removing calls? I am thinking that it would work something like the following.

```sh
# add new call
quicknav add current_call --call (or -c) new_call

# remove call
quicknav remove --call (or -c) to_remove
```

Or it could possibly be just a different command like `quicknav add-call` or something like that. What do you think? Any ideas?

**Comment by MrDogeBro** [comment]
What do you think about a param for adding and removing calls? I am thinking that it would work something like the following.

```sh
# add new call
quicknav add current_call --call (or -c) new_call

# remove call
quicknav remove --call (or -c) to_remove
```

Or it could possibly be just a different command like `quicknav add-call` or something like that. What do you think? Any ideas?

**Comment by parafoxia** [comment]
That could work yeah. I think either would work.

**Comment by MrDogeBro** [comment]
This should be completed now and is planned to release with v1.2.0.
