### ISSUE TITLE
Add common command aliases.

### ISSUE THREAD

**Issue by Jonxslays** [MrDogeBro/quicknav#28]
## Problem/Description
I find myself using common aliases, but being met with the `quicknav` error message.

```
quicknav ls
Error: The subcommand 'ls' wasn't recognized
	Did you mean 'list'?

If you believe you received this message in error, try re-running with 'quicknav -- ls'

USAGE:
    quicknav <SUBCOMMAND>

For more information try --help
```

## Desired Solution
Add common alias support in so that `ls` could be supported for `list` or `delete|del` could be supported for `remove`.

## Considered Alternatives
Not as important but maybe worth doing, is allowing -- to be in front of some subcommands like `quicknav --list`

**Comment by MrDogeBro** [comment]
This should also include some aliases such as `rm` for remove and other stuff that is common as well. Just basically making it easier to use with your know commands/aliases.

**Comment by Jonxslays** [comment]
yeah exactly :+1:
