### ISSUE TITLE
Make Sure Config Folder Exists

### ISSUE THREAD

**Issue by MrDogeBro** [MrDogeBro/quicknav#42]
## Bug Description

A simple, super easy fix that would make sure the `~/.config` folder exists on the machine because I was informed that there are some distros/machines that don't have a `~/.config` by default (or the first app has to create it, I don't know).

## Expected Behavior

If the `~/.config` folder does not exist, quicknav would just create the folder along with the quicknav config folder inside.

**Comment by DogeBroFlow** [comment]
This functionality has been released in v1.3.0.
