### ISSUE TITLE
Add message to `quicknav ls` when no shortcuts are found

### ISSUE THREAD

**Issue by Jonxslays** [MrDogeBro/quicknav#46]
## Problem/Description

I recently installed quicknav on a new machine, and before adding a shortcut I used `quicknav ls` to verify the installation succeeded. This was the first command that came to mind, obviously I could have used `--version` but oh well. The ouput from the `ls` subcommand is just 2 blank lines. 

## Desired Solution

It would be nice if a message was displayed, something like "You haven't set up any shortcuts yet, get started with `quicknav add`.".

## Considered Alternatives

N/A

## Additional Context

N/A

**Comment by MrDogeBro** [comment]
Yeah that sounds like it could be a good idea. Shouldn't be too hard to do either.

**Comment by DogeBroFlow** [comment]
This functionality has been released in v1.4.0.
